CREATE TABLE IF NOT EXISTS APM_SUBSCRIPTION_EXT (
    SUBSCRIPTION_ID INTEGER AUTO_INCREMENT,
    APP_ID INTEGER,
    SUBSCRIBER_ID INTEGER,
    SUBSCRIPTION_TYPE VARCHAR(50),
    SUBSCRIPTION_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EVALUATION_PERIOD INTEGER,
    EXPIRED_ON TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IS_PAID BOOLEAN DEFAULT FALSE,
    FOREIGN KEY(APP_ID) REFERENCES APM_APP(APP_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(SUBSCRIBER_ID) REFERENCES APM_SUBSCRIBER(SUBSCRIBER_ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (SUBSCRIPTION_ID),
    UNIQUE(APP_ID, SUBSCRIBER_ID)
)ENGINE INNODB;